SET REFERENTIAL_INTEGRITY = 0;

TRUNCATE TABLE persona;
TRUNCATE TABLE utente;
TRUNCATE TABLE personale;
TRUNCATE TABLE ruolo;
TRUNCATE TABLE libro;
TRUNCATE TABLE prenotazione;
TRUNCATE TABLE movimento_libro;
TRUNCATE TABLE indirizzo;
TRUNCATE TABLE persona_indirizzo;

SET REFERENTIAL_INTEGRITY = 1;
